# 🐼 Pandas — Data Analysis with Python

> **Step 2: Data Science**
>
> **Library 02: Pandas**
>
> **Date: February 3, 2024** 🎯
>
> **Class 18 — Pandas Fundamentals and Data Analysis**

Pandas is the second major library in my Data Science journey.

It is one of the most important Python libraries for working with structured data, data cleaning, data analysis, and exploratory data analysis.

The goal of this class is not only to learn Pandas functions, but to understand how to use Pandas to work with real-world datasets.

---
# 🎯 Learning Objectives

After this notebook you should be able to: create Series and DataFrames, load CSV/Excel/JSON/SQL data, inspect datasets, select with `loc`/`iloc`, filter, clean (missing values, duplicates, dtypes, text, dates), create/update/remove columns, sort, `groupby`, merge/concat, build pivot tables and crosstabs, work with time series, export data, and follow a full EDA workflow.

---
# 🎯 What is Pandas?

**Pandas** is an open-source Python library designed for:

- Data manipulation
- Data analysis
- Data cleaning
- Data transformation
- Data exploration
- Working with structured datasets
- Handling missing values
- Grouping and aggregating data
- Reading and writing data files

Pandas is especially useful when working with data represented as tables, rows, columns, CSV files, Excel files, SQL results and JSON data.

In [5]:
pip install pandas

Requirement already satisfied: pandas in /Users/waleedkhokhar/Documents/AI Engineer/.venv-1/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /Users/waleedkhokhar/Documents/AI Engineer/.venv-1/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/waleedkhokhar/Documents/AI Engineer/.venv-1/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/waleedkhokhar/Documents/AI Engineer/.venv-1/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

data = {
    "Name": ["Ali", "Ahmed", "Sara"],
    "Age": [22, 25, 21],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0    Ali   22     85
1  Ahmed   25     90
2   Sara   21     88

Output:

```text
    Name  Age  Marks
0    Ali   22     85
1  Ahmed   25     90
2   Sara   21     88
```

This table is called a **DataFrame**.

---
# 🧠 Why Learn Pandas?

Raw data is rarely ready for analysis. Real-world datasets can contain:

```text
Missing values · Duplicate rows · Incorrect data types · Invalid values
Inconsistent text · Unnecessary columns · Outliers · Different formats
```

Pandas provides tools to inspect, clean, transform, and analyze this data.

```text
Raw Data → Load → Inspect → Clean → Transform → Analyze → Visualize → Insights
```

This workflow is fundamental to Data Science.

---
# 1️⃣ Pandas Installation

```bash
pip install pandas
```

Verify the installation:

In [7]:
import pandas as pd

print(pd.__version__)

3.0.6

---
# 2️⃣ Importing Pandas

The standard way to import Pandas is `import pandas as pd`. The `pd` abbreviation is the commonly used convention.

---
# 3️⃣ Pandas Data Structures

Pandas mainly provides two important data structures: **Series** and **DataFrame**.

## 📌 Series

A Pandas Series is a one-dimensional labeled data structure. It contains values, an index and a data type.

In [8]:
import pandas as pd

marks = pd.Series([85, 90, 78, 92])

print(marks)
print("Values:", marks.values)
print("Index :", marks.index)
print("dtype :", marks.dtype)

0    85
1    90
2    78
3    92
dtype: int64
Values: [85 90 78 92]
Index : RangeIndex(start=0, stop=4, step=1)
dtype : int64

## 📊 DataFrame

A DataFrame is a two-dimensional labeled data structure that looks like a table or spreadsheet.

```text
Rows    → Records
Columns → Features / Variables
```

In [9]:
data = {
    "Name": ["Ali", "Ahmed", "Sara"],
    "Age": [22, 25, 21],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0    Ali   22     85
1  Ahmed   25     90
2   Sara   21     88

## 🔄 Series vs DataFrame

| Feature    | Series          | DataFrame        |
| ---------- | --------------- | ---------------- |
| Dimension  | 1D              | 2D               |
| Structure  | Single column   | Multiple columns |
| Similar to | List / column   | Table            |
| Has index  | Yes             | Yes              |
| Common use | Single variable | Complete dataset |

In [10]:
print(type(df["Age"]))   # a single column is a Series
print(type(df))          # the whole table is a DataFrame

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

---
# 🏗️ Creating DataFrames

A DataFrame can be created from many different sources.

## From Dictionary

In [11]:
data = {
    "Name": ["Ali", "Ahmed", "Sara"],
    "Age": [22, 25, 21],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks
0    Ali   22     85
1  Ahmed   25     90
2   Sara   21     88

## From List of Lists

In [12]:
data = [
    ["Ali", 22, 85],
    ["Ahmed", 25, 90],
    ["Sara", 21, 88]
]

df = pd.DataFrame(
    data,
    columns=["Name", "Age", "Marks"]
)

print(df)

    Name  Age  Marks
0    Ali   22     85
1  Ahmed   25     90
2   Sara   21     88

---
# 📂 Reading Data from Files

One of the most important uses of Pandas is loading datasets.

> 💡 So this notebook works on your machine without any external files, the next cell **creates sample files** (`students.csv`, `students.json`, `students.xlsx`) that we then read back.

In [13]:
import sqlite3

sample = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Name": ["Ali", "Ahmed", "Sara", "Hina", "Bilal", "Zara", "Usman", "Maryam"],
    "Age": [22, 25, 21, 23, 24, 20, 26, 22],
    "Gender": ["M", "M", "F", "F", "M", "F", "M", "F"],
    "City": ["Islamabad", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Islamabad", "Lahore"],
    "Marks": [85, 90, 78, 92, 45, 67, 88, 73],
})

sample.to_csv("students.csv", index=False)
sample.to_json("students.json")

try:
    sample.to_excel("students.xlsx", index=False)   # needs: pip install openpyxl
    excel_ok = True
except ImportError:
    excel_ok = False
    print("openpyxl not installed -> run: pip install openpyxl")

# tiny in-memory SQL database for the SQL example
connection = sqlite3.connect(":memory:")
sample.to_sql("students", connection, index=False)
print("Sample files created.")

openpyxl not installed -> run: pip install openpyxl
Sample files created.

## CSV Files

CSV is one of the most common formats used in Data Science.

In [14]:
df = pd.read_csv("students.csv")
df

   Student_ID    Name  Age Gender       City  Marks
0           1     Ali   22      M  Islamabad     85
1           2   Ahmed   25      M     Lahore     90
2           3    Sara   21      F    Karachi     78
3           4    Hina   23      F  Islamabad     92
4           5   Bilal   24      M     Lahore     45
5           6    Zara   20      F    Karachi     67
6           7   Usman   26      M  Islamabad     88
7           8  Maryam   22      F     Lahore     73

## Excel Files

In [15]:
if excel_ok:
    df_excel = pd.read_excel("students.xlsx")
    display(df_excel.head(3))

## JSON Files

In [16]:
df_json = pd.read_json("students.json")
df_json.head(3)

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
2           3   Sara   21      F    Karachi     78

## SQL Data

Pandas can also work with SQL query results. This makes it useful for backend and database-based applications as well.

In [17]:
query = "SELECT * FROM students WHERE Marks > 80"
df_sql = pd.read_sql(query, connection)
df_sql

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
2           4   Hina   23      F  Islamabad     92
3           7  Usman   26      M  Islamabad     88

---
# 🔍 Inspecting a Dataset

After loading a dataset, the first step is to understand what it contains.

```python
df.head()  df.tail()  df.shape  df.columns  df.index  df.info()  df.describe()
```

## 👀 `head()` — first rows (default 5)

In [18]:
df = pd.read_csv("students.csv")
df.head()

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
2           3   Sara   21      F    Karachi     78
3           4   Hina   23      F  Islamabad     92
4           5  Bilal   24      M     Lahore     45

In [19]:
df.head(3)

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
2           3   Sara   21      F    Karachi     78

## 🔚 `tail()` — last rows

In [20]:
df.tail()

   Student_ID    Name  Age Gender       City  Marks
3           4    Hina   23      F  Islamabad     92
4           5   Bilal   24      M     Lahore     45
5           6    Zara   20      F    Karachi     67
6           7   Usman   26      M  Islamabad     88
7           8  Maryam   22      F     Lahore     73

## 📐 `shape` — `(rows, columns)`

Example output `(100, 5)` means 100 rows and 5 columns.

In [21]:
print(df.shape)

(8, 6)

## 📋 `columns` — column names

In [22]:
print(df.columns)

Index(['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Marks'], dtype='str')

## 🔢 `index` — the DataFrame index

In [23]:
print(df.index)

RangeIndex(start=0, stop=8, step=1)

## ℹ️ `info()`

Shows number of rows, column names, non-null values, data types and memory usage.

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  8 non-null      int64
 1   Name        8 non-null      str
 2   Age         8 non-null      int64
 3   Gender      8 non-null      str
 4   City        8 non-null      str
 5   Marks       8 non-null      int64
dtypes: int64(3), str(3)
memory usage: 516.0 bytes

## 📊 `describe()`

Count, mean, std, min, 25%, median (50%), 75% and max for numerical columns.

In [25]:
df.describe()

       Student_ID       Age      Marks
count     8.00000   8.00000   8.000000
mean      4.50000  22.87500  77.250000
std       2.44949   2.03101  15.672998
min       1.00000  20.00000  45.000000
25%       2.75000  21.75000  71.500000
50%       4.50000  22.50000  81.500000
75%       6.25000  24.25000  88.500000
max       8.00000  26.00000  92.000000

---
# 🎯 Selecting Columns

In [26]:
print(df["Name"])          # one column -> Series
df[["Name", "Marks"]]      # multiple columns -> DataFrame

0       Ali
1     Ahmed
2      Sara
3      Hina
4     Bilal
5      Zara
6     Usman
7    Maryam
Name: Name, dtype: str

     Name  Marks
0     Ali     85
1   Ahmed     90
2    Sara     78
3    Hina     92
4   Bilal     45
5    Zara     67
6   Usman     88
7  Maryam     73

---
# 🔎 Selecting Rows

Pandas provides `loc` and `iloc`.

## 📍 `loc` — label-based

In [27]:
print(df.loc[0])
df.loc[0:2, ["Name", "Marks"]]   # NOTE: loc slices INCLUDE the end label

Student_ID            1
Name                Ali
Age                  22
Gender                M
City          Islamabad
Marks                85
Name: 0, dtype: object

    Name  Marks
0    Ali     85
1  Ahmed     90
2   Sara     78

## 🔢 `iloc` — position-based

In [28]:
print(df.iloc[0])
display(df.iloc[0:3])        # end position is EXCLUDED
df.iloc[0:3, 0:2]

Student_ID            1
Name                Ali
Age                  22
Gender                M
City          Islamabad
Marks                85
Name: 0, dtype: object

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
2           3   Sara   21      F    Karachi     78

   Student_ID   Name
0           1    Ali
1           2  Ahmed
2           3   Sara

## 🆚 `loc` vs `iloc`

| Method | Selection      |
| ------ | -------------- |
| `loc`  | Label-based    |
| `iloc` | Position-based |

`df.loc[2]` → row with **label** `2`. `df.iloc[2]` → the **third row** by position.

They only differ when the index is not `0,1,2,...` — try it:

In [29]:
tmp = df.set_index("Name")
print(tmp.loc["Sara", "Marks"])   # by label
print(tmp.iloc[2, -1])            # by position

78
78

---
# ✂️ Filtering Data

Filtering is one of the most important Pandas skills.

In [30]:
df[df["Marks"] > 80]   # students whose marks are greater than 80

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
3           4   Hina   23      F  Islamabad     92
6           7  Usman   26      M  Islamabad     88

## 🔗 Multiple Conditions

Use `&` (and), `|` (or), `~` (not). Always wrap each condition in parentheses.

In [31]:
print("AND:")
display(df[(df["Age"] > 20) & (df["Marks"] > 80)])
print("OR:")
display(df[(df["Age"] > 24) | (df["Marks"] > 90)])
print("NOT:")
df[~(df["Marks"] > 80)]

AND:

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
3           4   Hina   23      F  Islamabad     92
6           7  Usman   26      M  Islamabad     88

OR:

   Student_ID   Name  Age Gender       City  Marks
1           2  Ahmed   25      M     Lahore     90
3           4   Hina   23      F  Islamabad     92
6           7  Usman   26      M  Islamabad     88

NOT:

   Student_ID    Name  Age Gender     City  Marks
2           3    Sara   21      F  Karachi     78
4           5   Bilal   24      M   Lahore     45
5           6    Zara   20      F  Karachi     67
7           8  Maryam   22      F   Lahore     73

## 🔍 `isin()`

In [32]:
df[df["Name"].isin(["Ali", "Sara"])]

   Student_ID  Name  Age Gender       City  Marks
0           1   Ali   22      M  Islamabad     85
2           3  Sara   21      F    Karachi     78

## 🔎 `between()`

In [33]:
df[df["Age"].between(20, 25)]

   Student_ID    Name  Age Gender       City  Marks
0           1     Ali   22      M  Islamabad     85
1           2   Ahmed   25      M     Lahore     90
2           3    Sara   21      F    Karachi     78
3           4    Hina   23      F  Islamabad     92
4           5   Bilal   24      M     Lahore     45
5           6    Zara   20      F    Karachi     67
7           8  Maryam   22      F     Lahore     73

---
# 🧹 Missing Data

Real-world datasets often contain missing values.

```text
Name     Age     Salary
Ali      22      50000
Ahmed    NaN     60000
Sara     24      NaN
```

Important methods: `isna()`, `isnull()`, `notna()`, `dropna()`, `fillna()`.

In [34]:
import numpy as np

emp = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Sara"],
    "Age": [22, np.nan, 24],
    "Salary": [50000, 60000, np.nan]
})
emp

    Name   Age   Salary
0    Ali  22.0  50000.0
1  Ahmed   NaN  60000.0
2   Sara  24.0      NaN

## 🔍 Detecting Missing Values

In [35]:
print(emp.isna())
print()
print(emp.isna().sum())   # count per column

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

Name      0
Age       1
Salary    1
dtype: int64

## 🗑️ Removing Missing Values

`dropna()` removes rows containing missing values.

In [36]:
emp.dropna()

  Name   Age   Salary
0  Ali  22.0  50000.0

## 🩹 Filling Missing Values

In [37]:
emp2 = emp.copy()
emp2["Age"] = emp2["Age"].fillna(25)                        # fixed value
emp2["Salary"] = emp2["Salary"].fillna(emp2["Salary"].mean())  # statistic
emp2

    Name   Age   Salary
0    Ali  22.0  50000.0
1  Ahmed  25.0  60000.0
2   Sara  24.0  55000.0

---
# 🔄 Changing Data Types

Other useful types: `int`, `float`, `str`, `bool`, `datetime`, `category`.

In [38]:
print(emp2.dtypes)
emp2["Age"] = emp2["Age"].astype(int)
print()
print(emp2.dtypes)

Name          str
Age       float64
Salary    float64
dtype: object

Name          str
Age         int64
Salary    float64
dtype: object

---
# 📅 Working with Dates

Date handling is very important for real-world datasets.

In [39]:
dt = pd.DataFrame({"Date": ["2024-01-15", "2024-02-03", "2024-03-20"]})

dt["Date"] = pd.to_datetime(dt["Date"])

dt["Year"] = dt["Date"].dt.year
dt["Month"] = dt["Date"].dt.month
dt["Day"] = dt["Date"].dt.day
dt["Weekday"] = dt["Date"].dt.day_name()
dt

        Date  Year  Month  Day    Weekday
0 2024-01-15  2024      1   15     Monday
1 2024-02-03  2024      2    3   Saturday
2 2024-03-20  2024      3   20  Wednesday

---
# 📝 Working with Text

Pandas provides the `.str` accessor for text operations: `lower()`, `upper()`, `strip()`, `contains()`, `replace()`, `startswith()`, `endswith()`, `split()`, `len()`.

In [40]:
names = pd.Series(["  Ali ", "AHMED", "sara", "Hina Khan"])

print(names.str.lower().tolist())
print(names.str.upper().tolist())
print(names.str.strip().tolist())
print(names.str.contains("Ali").tolist())
print(names.str.startswith("s").tolist())
print(names.str.replace("a", "@").tolist())
print(names.str.split(" ").tolist())
print(names.str.len().tolist())

['  ali ', 'ahmed', 'sara', 'hina khan']
['  ALI ', 'AHMED', 'SARA', 'HINA KHAN']
['Ali', 'AHMED', 'sara', 'Hina Khan']
[True, False, False, False]
[False, False, True, False]
['  Ali ', 'AHMED', 's@r@', 'Hin@ Kh@n']
[['', '', 'Ali', ''], ['AHMED'], ['sara'], ['Hina', 'Khan']]
[6, 5, 4, 9]

---
# ➕ Creating New Columns

Pandas makes it easy to create calculated columns.

In [41]:
scores = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Sara"],
    "Math": [80, 45, 92],
    "Science": [70, 55, 88],
    "Marks": [75, 45, 90],
})

scores["Total"] = scores["Math"] + scores["Science"]
scores["Passed"] = scores["Marks"] >= 50
scores

    Name  Math  Science  Marks  Total  Passed
0    Ali    80       70     75    150    True
1  Ahmed    45       55     45    100   False
2   Sara    92       88     90    180    True

## ✏️ Updating Columns

`df['Age'] = df['Age'] + 1` increases every age by one.

In [42]:
u = df.copy()
u["Age"] = u["Age"] + 1
u[["Name", "Age"]].head(3)

    Name  Age
0    Ali   23
1  Ahmed   26
2   Sara   22

## 🗑️ Removing Columns

`inplace=True` modifies the original, but assigning the result is safer and usually clearer.

In [43]:
without_age = df.drop("Age", axis=1)     # safer: assign the result
without_age.head(3)

   Student_ID   Name Gender       City  Marks
0           1    Ali      M  Islamabad     85
1           2  Ahmed      M     Lahore     90
2           3   Sara      F    Karachi     78

## 🗑️ Removing Rows

In [44]:
display(df.drop(0).head(3))
df.drop([0, 1]).head(3)

   Student_ID   Name  Age Gender       City  Marks
1           2  Ahmed   25      M     Lahore     90
2           3   Sara   21      F    Karachi     78
3           4   Hina   23      F  Islamabad     92

   Student_ID   Name  Age Gender       City  Marks
2           3   Sara   21      F    Karachi     78
3           4   Hina   23      F  Islamabad     92
4           5  Bilal   24      M     Lahore     45

## 🔄 Renaming Columns

In [45]:
r = df.rename(columns={"Marks": "Score"})
r = r.rename(columns={"Name": "Student_Name", "Score": "Marks_Score"})
r.head(3)

   Student_ID Student_Name  Age Gender       City  Marks_Score
0           1          Ali   22      M  Islamabad           85
1           2        Ahmed   25      M     Lahore           90
2           3         Sara   21      F    Karachi           78

---
# 🔁 Sorting Data

In [46]:
display(df.sort_values("Marks").head(3))
display(df.sort_values("Marks", ascending=False).head(3))
df.sort_values(["Age", "Marks"], ascending=[True, False]).head(5)

   Student_ID    Name  Age Gender     City  Marks
4           5   Bilal   24      M   Lahore     45
5           6    Zara   20      F  Karachi     67
7           8  Maryam   22      F   Lahore     73

   Student_ID   Name  Age Gender       City  Marks
3           4   Hina   23      F  Islamabad     92
1           2  Ahmed   25      M     Lahore     90
6           7  Usman   26      M  Islamabad     88

   Student_ID    Name  Age Gender       City  Marks
5           6    Zara   20      F    Karachi     67
2           3    Sara   21      F    Karachi     78
0           1     Ali   22      M  Islamabad     85
7           8  Maryam   22      F     Lahore     73
3           4    Hina   23      F  Islamabad     92

---
# 🧮 Aggregation

Common functions: `sum()`, `mean()`, `median()`, `min()`, `max()`, `count()`, `std()`, `var()`.

In [47]:
print("Mean :", df["Marks"].mean())
print("Max  :", df["Marks"].max())
print("Min  :", df["Marks"].min())
print("Std  :", df["Marks"].std())

Mean : 77.25
Max  : 92
Min  : 45
Std  : 15.672997707613472

---
# 📊 GroupBy

`groupby()` is one of the most important Pandas concepts. It allows us to group data based on a category and perform calculations.

In [48]:
employees = pd.DataFrame({
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Department": ["IT", "IT", "HR", "HR", "Sales", "Sales"],
    "Salary": [90000, 110000, 60000, 65000, 70000, 85000],
    "Age": [28, 35, 30, 41, 26, 38],
})

employees.groupby("Department")["Salary"].mean()   # average salary per department

Department
HR        62500.0
IT       100000.0
Sales     77500.0
Name: Salary, dtype: float64

## 📦 GroupBy with Multiple Aggregations

In [49]:
employees.groupby("Department")["Salary"].agg(["count", "mean", "min", "max"])

            count      mean    min     max
Department
HR              2   62500.0  60000   65000
IT              2  100000.0  90000  110000
Sales           2   77500.0  70000   85000

---
# 🔗 Combining DataFrames

Important operations: `concat()`, `merge()`, `join()`.

## ➕ `concat()`

In [50]:
df1 = pd.DataFrame({"Name": ["Ali", "Sara"], "Marks": [85, 88]})
df2 = pd.DataFrame({"Name": ["Hina", "Bilal"], "Marks": [92, 45]})

pd.concat([df1, df2], ignore_index=True)          # vertical

    Name  Marks
0    Ali     85
1   Sara     88
2   Hina     92
3  Bilal     45

In [51]:
pd.concat([df1, df2], axis=1)                     # horizontal

   Name  Marks   Name  Marks
0   Ali     85   Hina     92
1  Sara     88  Bilal     45

## 🔗 `merge()`

Combines datasets using common columns. Similar to a SQL JOIN.

In [52]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Ali", "Sara", "Hina", "Bilal"],
})
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 5],
    "amount": [250, 100, 400, 75],
})

pd.merge(customers, orders, on="customer_id")     # inner (default)

   customer_id  name  order_id  amount
0            1   Ali       101     250
1            1   Ali       102     100
2            2  Sara       103     400

In [53]:
for how in ["inner", "left", "right", "outer"]:
    print(f"--- {how.upper()} ---")
    display(pd.merge(customers, orders, on="customer_id", how=how))

--- INNER ---

   customer_id  name  order_id  amount
0            1   Ali       101     250
1            1   Ali       102     100
2            2  Sara       103     400

--- LEFT ---

   customer_id   name  order_id  amount
0            1    Ali     101.0   250.0
1            1    Ali     102.0   100.0
2            2   Sara     103.0   400.0
3            3   Hina       NaN     NaN
4            4  Bilal       NaN     NaN

--- RIGHT ---

   customer_id  name  order_id  amount
0            1   Ali       101     250
1            1   Ali       102     100
2            2  Sara       103     400
3            5   NaN       104      75

--- OUTER ---

   customer_id   name  order_id  amount
0            1    Ali     101.0   250.0
1            1    Ali     102.0   100.0
2            2   Sara     103.0   400.0
3            3   Hina       NaN     NaN
4            4  Bilal       NaN     NaN
5            5    NaN     104.0    75.0

## 🆚 Pandas Merge and SQL JOIN

| Pandas        | SQL               |
| ------------- | ----------------- |
| `merge()`     | `JOIN`            |
| `on=`         | `ON`              |
| `how="inner"` | `INNER JOIN`      |
| `how="left"`  | `LEFT JOIN`       |
| `how="right"` | `RIGHT JOIN`      |
| `how="outer"` | `FULL OUTER JOIN` |

## `join()` — merges on the **index**

In [54]:
customers.set_index("customer_id").join(orders.set_index("customer_id"), how="left")

              name  order_id  amount
customer_id
1              Ali     101.0   250.0
1              Ali     102.0   100.0
2             Sara     103.0   400.0
3             Hina       NaN     NaN
4            Bilal       NaN     NaN

---
# 📋 Removing Duplicates

In [55]:
dup = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ali", "Hina"],
    "Age": [22, 21, 22, 23],
})

print(dup.duplicated())
print("Duplicate count:", dup.duplicated().sum())
dup.drop_duplicates()

0    False
1    False
2     True
3    False
dtype: bool
Duplicate count: 1

   Name  Age
0   Ali   22
1  Sara   21
3  Hina   23

---
# 🧹 Data Cleaning

Data cleaning is one of the most important parts of Data Science.

```text
Raw Dataset → Check Shape → Check Data Types → Check Missing Values → Check Duplicates
→ Fix Incorrect Values → Clean Text → Convert Data Types → Handle Outliers → Clean Dataset
```

A complete example on a deliberately messy dataset:

In [56]:
messy = pd.DataFrame({
    "Name": ["  ali ", "SARA", "Ahmed", "SARA", "hina"],
    "Age": ["22", "21", None, "21", "23"],
    "City": ["islamabad", "LAHORE ", "Karachi", "LAHORE ", None],
    "Marks": [85, 88, 90, 88, 92],
})
print("BEFORE"); display(messy); print(messy.dtypes)

clean = messy.copy()
clean["Name"] = clean["Name"].str.strip().str.title()            # fix text
clean["City"] = clean["City"].str.strip().str.title()
clean["Age"] = pd.to_numeric(clean["Age"])                        # fix dtype
clean["Age"] = clean["Age"].fillna(clean["Age"].median()).astype(int)  # missing
clean["City"] = clean["City"].fillna("Unknown")
clean = clean.drop_duplicates().reset_index(drop=True)            # duplicates

print("AFTER"); display(clean); print(clean.dtypes)

BEFORE

     Name  Age       City  Marks
0    ali    22  islamabad     85
1    SARA   21    LAHORE      88
2   Ahmed  NaN    Karachi     90
3    SARA   21    LAHORE      88
4    hina   23        NaN     92

Name       str
Age        str
City       str
Marks    int64
dtype: object
AFTER

    Name  Age       City  Marks
0    Ali   22  Islamabad     85
1   Sara   21     Lahore     88
2  Ahmed   21    Karachi     90
3   Hina   23    Unknown     92

Name       str
Age      int64
City       str
Marks    int64
dtype: object

---
# 📊 Data Analysis

Once the data is clean, we can analyze it.

In [57]:
print(employees["Salary"].mean())
display(employees.groupby("Department")["Salary"].mean())
display(employees.sort_values("Salary", ascending=False))
employees[employees["Salary"] > 80000]

80000.0

Department
HR        62500.0
IT       100000.0
Sales     77500.0
Name: Salary, dtype: float64

  Employee Department  Salary  Age
1        B         IT  110000   35
0        A         IT   90000   28
5        F      Sales   85000   38
4        E      Sales   70000   26
3        D         HR   65000   41
2        C         HR   60000   30

  Employee Department  Salary  Age
0        A         IT   90000   28
1        B         IT  110000   35
5        F      Sales   85000   38

---
# 📈 Exploratory Data Analysis

EDA means exploring a dataset to understand structure, distributions, relationships, patterns, missing values, outliers, categories and trends.

```text
Load → Understand → Clean → Analyze Columns → Explore Relationships → Find Patterns → Visualize → Insights
```

Visualization will later be handled using Matplotlib and Seaborn.

---
# 📊 Pivot Tables

In [58]:
sales = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "North", "South"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [100, 150, 200, 120, 80, 90],
})

pd.pivot_table(
    sales,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum"
)

Product    A    B
Region
North    180  150
South    200  210

Pivot tables are useful for business analysis, sales analysis, reporting and summarizing large datasets.

---
# 🪟 Crosstab

Creates a frequency table between categories.

In [59]:
dept = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Sales", "IT"],
    "Gender": ["M", "F", "F", "F", "M", "M"],
})

pd.crosstab(dept["Department"], dept["Gender"])

Gender      F  M
Department
HR          2  0
IT          1  2
Sales       0  1

---
# 🔢 Unique Values

These are extremely useful during data exploration.

In [60]:
print(df["City"].unique())
print(df["City"].nunique())
print(df["City"].value_counts())

<StringArray>
['Islamabad', 'Lahore', 'Karachi']
Length: 3, dtype: str
3
City
Islamabad    3
Lahore       3
Karachi      2
Name: count, dtype: int64

---
# 📊 Sampling Data

Get random rows — useful when inspecting large datasets.

In [61]:
df.sample(3, random_state=42)

   Student_ID   Name  Age Gender       City  Marks
1           2  Ahmed   25      M     Lahore     90
5           6   Zara   20      F    Karachi     67
0           1    Ali   22      M  Islamabad     85

---
# 🔄 Resetting Index

After filtering or removing rows, indexes may become non-sequential.

In [62]:
filtered = df[df["Marks"] > 80]
display(filtered)
filtered.reset_index(drop=True)

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
3           4   Hina   23      F  Islamabad     92
6           7  Usman   26      M  Islamabad     88

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
2           4   Hina   23      F  Islamabad     92
3           7  Usman   26      M  Islamabad     88

---
# 🧠 Setting an Index

A column can be used as the DataFrame index.

In [63]:
indexed = df.set_index("Student_ID")
display(indexed.head(3))
indexed.reset_index().head(3)

             Name  Age Gender       City  Marks
Student_ID
1             Ali   22      M  Islamabad     85
2           Ahmed   25      M     Lahore     90
3            Sara   21      F    Karachi     78

   Student_ID   Name  Age Gender       City  Marks
0           1    Ali   22      M  Islamabad     85
1           2  Ahmed   25      M     Lahore     90
2           3   Sara   21      F    Karachi     78

---
# 📁 Exporting Data

Pandas can save processed data into different formats.

```text
Read → Clean → Analyze → Transform → Export
```

In [64]:
df.to_csv("cleaned_data.csv", index=False)
df.to_json("cleaned_data.json")
if excel_ok:
    df.to_excel("cleaned_data.xlsx", index=False)
print("Exported: cleaned_data.csv / .json / .xlsx")

Exported: cleaned_data.csv / .json / .xlsx

---
# ⚡ Vectorized Operations

Instead of manually looping through every row, apply the operation to the entire column. This makes data operations concise and efficient.

In [65]:
v = employees.copy()
v["Salary"] = v["Salary"] * 1.10
v

  Employee Department    Salary  Age
0        A         IT   99000.0   28
1        B         IT  121000.0   35
2        C         HR   66000.0   30
3        D         HR   71500.0   41
4        E      Sales   77000.0   26
5        F      Sales   93500.0   38

---
# 🧩 `apply()`

Useful, but vectorized operations should generally be preferred when a direct vectorized solution exists.

In [66]:
def add_bonus(salary):
    return salary + 5000

a = employees.copy()
a["New_Salary"] = a["Salary"].apply(add_bonus)
a["New_Salary_Lambda"] = a["Salary"].apply(lambda salary: salary + 5000)
a

  Employee Department  Salary  Age  New_Salary  New_Salary_Lambda
0        A         IT   90000   28       95000              95000
1        B         IT  110000   35      115000             115000
2        C         HR   60000   30       65000              65000
3        D         HR   65000   41       70000              70000
4        E      Sales   70000   26       75000              75000
5        F      Sales   85000   38       90000              90000

---
# 🧠 `map()`

Useful for transforming values in a Series.

In [67]:
g = df.copy()
mapping = {"M": "Male", "F": "Female"}
g["Gender"] = g["Gender"].map(mapping)
g[["Name", "Gender"]].head(4)

    Name  Gender
0    Ali    Male
1  Ahmed    Male
2   Sara  Female
3   Hina  Female

---
# 🔄 `replace()`

In [68]:
g2 = df.copy()
g2["Gender"] = g2["Gender"].replace({"M": "Male", "F": "Female"})
g2[["Name", "Gender"]].head(4)

    Name  Gender
0    Ali    Male
1  Ahmed    Male
2   Sara  Female
3   Hina  Female

---
# 🧮 `query()`

A readable way to filter data.

In [69]:
display(df.query("Age > 22"))
df.query("Age > 22 and Marks > 80")

   Student_ID   Name  Age Gender       City  Marks
1           2  Ahmed   25      M     Lahore     90
3           4   Hina   23      F  Islamabad     92
4           5  Bilal   24      M     Lahore     45
6           7  Usman   26      M  Islamabad     88

   Student_ID   Name  Age Gender       City  Marks
1           2  Ahmed   25      M     Lahore     90
3           4   Hina   23      F  Islamabad     92
6           7  Usman   26      M  Islamabad     88

---
# 🗂️ MultiIndex

Creates a hierarchical index; useful for more advanced analysis.

In [70]:
mi = employees.set_index(["Department", "Employee"])
display(mi)
mi.loc["IT"]

                     Salary  Age
Department Employee
IT         A          90000   28
           B         110000   35
HR         C          60000   30
           D          65000   41
Sales      E          70000   26
           F          85000   38

          Salary  Age
Employee
A          90000   28
B         110000   35

---
# 📅 Time Series Data

Important concepts: datetime, date ranges, resampling, time-based indexing, time differences, rolling calculations.

In [71]:
dates = pd.date_range(
    start="2024-01-01",
    periods=10
)

print(dates)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[us]', freq='D')

In [72]:
import numpy as np
np.random.seed(0)
ts = pd.DataFrame({
    "Date": pd.date_range("2024-01-01", periods=60),
    "Sales": np.random.randint(100, 500, 60),
}).set_index("Date")

print(ts.loc["2024-01-10":"2024-01-15"])       # time-based indexing
print(ts.resample("MS").sum())                 # monthly totals (resampling)

            Sales
Date
2024-01-10    311
2024-01-11    377
2024-01-12    342
2024-01-13    392
2024-01-14    187
2024-01-15    170
            Sales
Date
2024-01-01   8878
2024-02-01   8561

---
# 📈 Rolling Calculations

A moving average over three observations:

In [73]:
ts["Rolling_Average"] = ts["Sales"].rolling(3).mean()
ts.head(6)

            Sales  Rolling_Average
Date
2024-01-01    272              NaN
2024-01-02    147              NaN
2024-01-03    217       212.000000
2024-01-04    292       218.666667
2024-01-05    423       310.666667
2024-01-06    351       355.333333

---
# 🧪 Practical Data Science Workflow

```text
Dataset → Load with Pandas → Inspect → (Missing Values | Duplicates) → Clean
→ Data Types → Transform → Filter → Group & Analyze → Find Patterns → Visualization → Insights
```

---
# 🌍 Real-World Pandas Examples

* 🛒 **E-Commerce** — orders, customers, products, revenue, discounts, shipping, sales trends
* 🏦 **Finance** — transactions, revenue, expenses, investments, financial trends
* 🏥 **Healthcare** — patients, medical records, treatments, test results, hospital data
* 🎓 **Education** — students, marks, attendance, courses, performance
* 💼 **Business** — employees, departments, salaries, sales, customers, KPIs

---
# 🤖 Pandas in Machine Learning

```text
CSV → Pandas → Load → Clean → Explore → Transform → Separate Features & Target → NumPy / ML Framework → Model
```

Here `X` = Features and `y` = Target.

In [74]:
ml = pd.DataFrame({
    "Age": [25, 30, 35, 40],
    "Income": [40000, 55000, 70000, 90000],
    "Experience": [2, 6, 10, 15],
    "Salary": [45000, 60000, 80000, 100000],
})

X = ml[["Age", "Income", "Experience"]]

y = ml["Salary"]

print(X.shape, y.shape)
X.to_numpy()   # convert to a NumPy array for ML libraries

(4, 3) (4,)

array([[   25, 40000,     2],
       [   30, 55000,     6],
       [   35, 70000,    10],
       [   40, 90000,    15]])

---
# 🐼 Pandas vs NumPy

| Feature             | NumPy               | Pandas             |
| ------------------- | ------------------- | ------------------ |
| Main purpose        | Numerical computing | Data analysis      |
| Main structure      | ndarray             | Series / DataFrame |
| Labels              | Limited             | Built-in           |
| Tables              | Not its main focus  | Excellent          |
| Missing data        | Basic tools         | Extensive tools    |
| CSV handling        | Not primary         | Excellent          |
| Data cleaning       | Limited             | Extensive          |
| Grouping            | Limited             | Powerful           |
| SQL-like operations | Limited             | Merge / Join       |
| Data Science        | Foundation          | Core tool          |

```text
NumPy  → Numerical Arrays
Pandas → Structured Data
```

## 🔗 Connection With NumPy

```text
NumPy → Numerical Arrays → Pandas → DataFrames → Data Analysis
```

In [75]:
import numpy as np
import pandas as pd

numbers = np.array([10, 20, 30, 40])

df_np = pd.DataFrame({
    "Numbers": numbers
})

print(df_np)

   Numbers
0       10
1       20
2       30
3       40

---
# 🧠 Important Pandas Concepts

```text
Pandas
│
├── Series / DataFrame
├── Creating Data
├── Reading Files (CSV, Excel, JSON, SQL)
├── Inspecting Data (head, tail, info, describe, shape)
├── Selecting Data ([], loc, iloc)
├── Filtering (Conditions, isin, between)
├── Cleaning (Missing Values, Duplicates, Data Types, Text Cleaning)
├── Transformation (New Columns, apply, map, replace)
├── Sorting · GroupBy · Aggregation
├── Merge · Join · Concat
├── Pivot Tables · Crosstab
├── Time Series · Rolling Operations
└── Exporting Data
```

---
# 📋 Important Pandas Functions

| Function / Method      | Purpose                  |
| ---------------------- | ------------------------ |
| `pd.Series()`          | Create a Series          |
| `pd.DataFrame()`       | Create a DataFrame       |
| `pd.read_csv()`        | Read CSV                 |
| `pd.read_excel()`      | Read Excel               |
| `pd.read_json()`       | Read JSON                |
| `df.head()`            | First rows               |
| `df.tail()`            | Last rows                |
| `df.info()`            | Dataset information      |
| `df.describe()`        | Statistical summary      |
| `df.shape`             | Rows and columns         |
| `df.columns`           | Column names             |
| `df.dtypes`            | Data types               |
| `df.loc[]`             | Label-based selection    |
| `df.iloc[]`            | Position-based selection |
| `df.isna()`            | Detect missing values    |
| `df.dropna()`          | Remove missing values    |
| `df.fillna()`          | Fill missing values      |
| `df.drop_duplicates()` | Remove duplicates        |
| `df.sort_values()`     | Sort data                |
| `df.groupby()`         | Group data               |
| `pd.merge()`           | Merge DataFrames         |
| `pd.concat()`          | Concatenate DataFrames   |
| `df.rename()`          | Rename columns           |
| `df.drop()`            | Remove rows/columns      |
| `df.value_counts()`    | Count values             |
| `df.unique()`          | Get unique values        |
| `df.nunique()`         | Count unique values      |
| `df.apply()`           | Apply function           |
| `df.map()`             | Map values               |
| `pd.to_datetime()`     | Convert to datetime      |
| `pd.pivot_table()`     | Create pivot table       |
| `df.to_csv()`          | Export CSV               |
| `df.to_excel()`        | Export Excel             |
| `df.to_json()`         | Export JSON              |

---
# 🎯 Learning Goals

After completing Pandas, I should be able to:

* Understand what Pandas is and why it is used in Data Science.
* Understand Series and DataFrame; create DataFrames.
* Load datasets from different file formats and inspect them.
* Select rows and columns; understand `loc` and `iloc`.
* Filter datasets.
* Work with missing values, remove duplicates, change data types.
* Clean text data and work with dates.
* Create, update and remove columns.
* Sort, group and aggregate data.
* Merge and concatenate datasets.
* Create pivot tables; analyze categorical data.
* Work with time-series data.
* Export cleaned datasets.
* Prepare data for Machine Learning.
* Perform the Pandas portion of an EDA workflow.

---
# 🧪 Practice Exercises

Write your solution in the code cell under each exercise.

## Exercise 01 — Create a DataFrame

Create a student DataFrame containing `Name, Age, Gender, Marks, City`.

Perform:

* Display the DataFrame
* Display first rows
* Display last rows
* Check shape
* Check columns
* Check data types

## Exercise 02 — Student Analysis

Using a student dataset calculate:

* Average marks
* Highest marks
* Lowest marks
* Number of students
* Students above average
* Students who passed

## Exercise 03 — Filtering

Filter students:

* Age > 20
* Marks > 80
* Marks between 60 and 90
* Students from Islamabad
* Students who passed

## Exercise 04 — Missing Values

Create a dataset containing missing values. Practice:

* Detect missing values
* Count missing values
* Remove missing values
* Fill missing values
* Fill numerical missing values using the mean

## Exercise 05 — Data Cleaning

Create a dataset containing duplicate rows, missing values, incorrect capitalization, extra spaces and incorrect data types.

Clean the complete dataset.

## Exercise 06 — GroupBy

Create an employee dataset (`Employee, Department, Salary, Age`).

Calculate:

* Average salary by department
* Maximum salary by department
* Minimum salary by department
* Number of employees by department

## Exercise 07 — Merge

Create two DataFrames, `Customers` and `Orders`, connected by `customer_id`.

Practice: inner, left, right and outer merge.

## Exercise 08 — Sales Analysis

Create a sales dataset (`Date, Product, Category, Region, Quantity, Price`).

Calculate:

* Total revenue
* Average order value
* Best-selling product
* Revenue by category
* Revenue by region
* Monthly sales
* Highest sales day

---
# 🚀 Mini Project — Student Performance Analysis

Dataset columns: `Student_ID, Name, Age, Gender, City, Study_Hours, Attendance, Math, Science, English`.

Below is a generated dataset so you can complete each step right away.

### Step 1 — Load Data

In [84]:
np.random.seed(7)
n = 30
project = pd.DataFrame({
    "Student_ID": range(1, n + 1),
    "Name": [f"Student_{i}" for i in range(1, n + 1)],
    "Age": np.random.randint(18, 26, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "City": np.random.choice(["Islamabad", "Lahore", "Karachi"], n),
    "Study_Hours": np.random.randint(1, 9, n).astype(float),
    "Attendance": np.random.randint(60, 100, n).astype(float),
    "Math": np.random.randint(30, 100, n).astype(float),
    "Science": np.random.randint(30, 100, n).astype(float),
    "English": np.random.randint(30, 100, n).astype(float),
})
# add some dirt
project.loc[3, "Math"] = np.nan
project.loc[8, "Attendance"] = np.nan
project = pd.concat([project, project.iloc[[0]]], ignore_index=True)   # a duplicate row
project.to_csv("student_performance.csv", index=False)

sp = pd.read_csv("student_performance.csv")
sp.head()

,Student_ID,Name,Age,Gender,City,Study_Hours,Attendance,Math,Science,English
0,1,Student_1,25,Female,Karachi,6.0,72.0,51.0,43.0,35.0
1,2,Student_2,22,Male,Lahore,4.0,72.0,34.0,73.0,51.0
2,3,Student_3,19,Male,Islamabad,2.0,75.0,36.0,31.0,46.0
3,4,Student_4,24,Female,Islamabad,2.0,89.0,NaN,61.0,41.0
4,5,Student_5,21,Female,Islamabad,5.0,68.0,86.0,44.0,62.0

### Step 2 — Inspect

Check shape, columns, data types, missing values, duplicates.

In [85]:
print("Shape     :", sp.shape)
print("Columns   :", list(sp.columns))
print(sp.dtypes)
print("Missing   :\n", sp.isna().sum())
print("Duplicates:", sp.duplicated().sum())

Shape     : (31, 10)
Columns   : ['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Study_Hours', 'Attendance', 'Math', 'Science', 'English']
Student_ID       int64
Name               str
Age              int64
Gender             str
City               str
Study_Hours    float64
Attendance     float64
Math           float64
Science        float64
English        float64
dtype: object
Missing   :
 Student_ID     0
Name           0
Age            0
Gender         0
City           0
Study_Hours    0
Attendance     1
Math           1
Science        0
English        0
dtype: int64
Duplicates: 1

### Step 3 — Clean

In [86]:
sp = sp.drop_duplicates().reset_index(drop=True)
sp["Math"] = sp["Math"].fillna(sp["Math"].mean())
sp["Attendance"] = sp["Attendance"].fillna(sp["Attendance"].median())
print(sp.isna().sum().sum(), "missing values left")

0 missing values left

### Step 4 — Transform

Create `Total_Marks`, `Average_Marks`, `Pass_Fail`, `Performance`.

In [87]:
subjects = ["Math", "Science", "English"]
sp["Total_Marks"] = sp[subjects].sum(axis=1)
sp["Average_Marks"] = sp[subjects].mean(axis=1).round(2)
sp["Pass_Fail"] = np.where(sp["Average_Marks"] >= 50, "Pass", "Fail")
sp["Performance"] = pd.cut(
    sp["Average_Marks"],
    bins=[0, 50, 65, 80, 100],
    labels=["Poor", "Average", "Good", "Excellent"]
)
sp.head()

,Student_ID,Name,Age,Gender,City,Study_Hours,Attendance,Math,Science,English,Total_Marks,Average_Marks,Pass_Fail,Performance
0,1,Student_1,25,Female,Karachi,6.0,72.0,51.000000,43.0,35.0,129.000000,43.00,Fail,Poor
1,2,Student_2,22,Male,Lahore,4.0,72.0,34.000000,73.0,51.0,158.000000,52.67,Pass,Average
2,3,Student_3,19,Male,Islamabad,2.0,75.0,36.000000,31.0,46.0,113.000000,37.67,Fail,Poor
3,4,Student_4,24,Female,Islamabad,2.0,89.0,63.482759,61.0,41.0,165.482759,55.16,Pass,Average
4,5,Student_5,21,Female,Islamabad,5.0,68.0,86.000000,44.0,62.0,192.000000,64.00,Pass,Average

### Step 5 — Analyze

In [88]:
print("Average marks       :", round(sp["Average_Marks"].mean(), 2))
print("Highest marks       :", sp["Total_Marks"].max())
print("Lowest marks        :", sp["Total_Marks"].min())
print("Average attendance  :", round(sp["Attendance"].mean(), 2))
print("Average study hours :", round(sp["Study_Hours"].mean(), 2))

print("\nTop 5 students:")
display(sp.nlargest(5, "Total_Marks")[["Name", "Total_Marks", "Average_Marks"]])

print("Students below average:", (sp["Average_Marks"] < sp["Average_Marks"].mean()).sum())

print("\nPerformance by city:")
display(sp.groupby("City")["Average_Marks"].mean().round(2))
print("Performance by gender:")
display(sp.groupby("Gender")["Average_Marks"].mean().round(2))

Average marks       : 65.07
Highest marks       : 255.0
Lowest marks        : 113.0
Average attendance  : 79.2
Average study hours : 4.83

Top 5 students:

          Name  Total_Marks  Average_Marks
9   Student_10        255.0          85.00
24  Student_25        247.0          82.33
13  Student_14        235.0          78.33
5    Student_6        229.0          76.33
8    Student_9        218.0          72.67

Students below average: 11

Performance by city:

City
Islamabad    61.35
Karachi      68.38
Lahore       66.15
Name: Average_Marks, dtype: float64

Performance by gender:

Gender
Female    64.01
Male      66.00
Name: Average_Marks, dtype: float64

### Step 6 — Prepare for Visualization

Summary tables that can later be plotted with Matplotlib / Seaborn.

In [89]:
city_summary = sp.groupby("City").agg(
    Students=("Student_ID", "count"),
    Avg_Marks=("Average_Marks", "mean"),
    Avg_Attendance=("Attendance", "mean"),
).round(2)

performance_counts = sp["Performance"].value_counts().sort_index()

display(city_summary)
performance_counts

           Students  Avg_Marks  Avg_Attendance
City
Islamabad        10      61.35           77.90
Karachi           7      68.38           81.29
Lahore           13      66.15           79.08

Performance
Poor          4
Average       7
Good         17
Excellent     2
Name: count, dtype: int64

---
# 💼 Interview Questions

### Beginner
1. What is Pandas?
2. Why is Pandas used?
3. What is a Series?
4. What is a DataFrame?
5. What is the difference between Series and DataFrame?
6. How do you create a DataFrame?
7. How do you read a CSV file?
8. What does `head()` do?
9. What does `info()` do?
10. What does `describe()` do?

### Intermediate
11. What is the difference between `loc` and `iloc`?
12. How do you filter rows in Pandas?
13. How do you handle missing values?
14. What is the difference between `dropna()` and `fillna()`?
15. How do you remove duplicate rows?
16. How do you change a column's data type?
17. How do you rename columns?
18. How do you sort a DataFrame?
19. What is `groupby()`?
20. What is aggregation?

### Advanced Foundation
21. What is the difference between `merge()`, `join()`, and `concat()`?
22. How does Pandas handle indexes?
23. What is a MultiIndex?
24. What is vectorization?
25. When should you use `apply()`?
26. What is the difference between `map()` and `apply()`?
27. How do you work with datetime data?
28. What are pivot tables?
29. How does Pandas support EDA?
30. How is Pandas used before Machine Learning?

---
# 🧠 Mental Model

Think of Pandas as a tool that turns raw data into understandable information.

```text
CSV File → pd.read_csv() → DataFrame → df.info() → Clean Data → Filter → GroupBy → Statistics → Visualization → Insights
```

---
# 📁 Folder Structure

```text
02-Data-Science/
├── README.md
├── 01-NumPy/
│   ├── README.md
│   └── class17.ipynb
└── 02-Pandas/
    ├── README.md
    └── class18.ipynb
```

---
# 🚀 Data Science Roadmap

```text
Step 2 — Data Science
│
├── 01 NumPy          ✅
├── 02 Pandas         ← Current
├── 03 Matplotlib
├── 04 Seaborn
├── 05 Data Cleaning
├── 06 Exploratory Data Analysis
└── 07 Statistics
```

Then: `Data Science → Machine Learning → Deep Learning → Generative AI / LLMs → Agentic AI → MLOps → AI Engineering`

---
# 🎯 Final Goal

The goal of learning Pandas is not simply to memorize functions. The goal is to become comfortable working with real-world structured data.

```text
Raw Dataset → Load → Inspect → Clean → Transform → Filter → Group → Analyze → Prepare for Visualization / ML
```

This creates the practical Data Science foundation required for the next stages of my AI Engineering journey.

---
# 🔑 Key Takeaways

* Pandas is a major Python library for data analysis.
* The two core structures are `Series` and `DataFrame`.
* DataFrames represent structured tabular data.
* Pandas can read CSV, Excel, JSON, and SQL data.
* `head()`, `tail()`, `info()`, and `describe()` help understand datasets.
* `loc` and `iloc` are important for selecting data.
* Boolean filtering allows specific records to be selected.
* Missing values can be detected, removed, or filled.
* Pandas provides powerful data-cleaning tools.
* `groupby()` is essential for grouped analysis.
* `merge()`, `join()`, and `concat()` allow datasets to be combined.
* Pivot tables and crosstabs help summarize data.
* Pandas is heavily used during EDA.
* Pandas prepares data for visualization and Machine Learning.
* Pandas and NumPy work closely together.

> **NumPy gives me the numerical foundation. Pandas gives me the tools to work with structured data.**

---
# 📚 Navigation

**Previous:** [← NumPy — Class 17](../01-NumPy/README.md)  |  **Current:** Pandas — Class 18  |  **Next:** Matplotlib — Class 19

# 🐼 Data Science Journey

> **Learn the fundamentals → Work with real data → Analyze → Visualize → Build Machine Learning systems**

**Python → NumPy → Pandas → Matplotlib → Seaborn → EDA → Statistics → Machine Learning**